### ISSUE TITLE
Shellfire VPN for Windows VPN Connection is established but no data coming through

### ISSUE THREAD

**Issue by flogat** [shell-fire/shellfire-vpn#36] opened 2020-10-12 18:44 UTC
- DNS seems to be working, using Windows 7. Sent log (October 12, 2020, 14:08 CEST)
- On Windows 10, the same error happens. Sent log (14:35 CEST)
- Sending log did not work because of no internet. Sent log again now (Win 7 and 10: 14:50h )

**Comment by flogat** [comment] 2020-10-14 18:47
- Will need more details with regard to the actual steps performed before to reproduce this.
- Might be related to the multiple start of Shellfire VPN #34 
- Seems to happen to me when stopping/killing the GUI process while the vpn connection is enabled - can you confirm this @mbehrsf  ?
- I suggest a retest first with a new build to see if this still occurs...

**Comment by mbehrsf** [comment] 2020-10-16 14:57
I still have the issue on both Win 7 and 10. I sent log reports today at 16:49h and 16:54.  I believe this is the cause:

Fri Oct 16 07:48:18 2020 ERROR: Windows ipconfig command failed: returned error code 2

**Comment by mbehrsf** [comment] 2020-11-05 13:45
I still see the issue with the latest build, both on Win 7 and 10. Has nothing to do with multiple instances running or stopping/killing.

Sent logs at 14:24h and 14:39h. The error message looks different though, but the result is the same.

**Comment by flogat** [comment] 2020-11-07 19:44
@mbehrsf can you confirm that, as we discussed bilatterally, this was related to your ISP and the software works fine if a server is selected that does not need udp on port 53 ?

**Comment by flogat** [comment] 2020-11-13 15:21
@mbehrsf ?

**Comment by mbehrsf** [comment] 2020-11-16 14:52
Yes, I just confirmed that the problem also happens with other OpenVPN setups on udp 53. Closing.

**Closed as completed by mbehrsf** 2020-11-16 14:52 UTC
